### ISSUE TITLE
Why is the value of loglikehood positive?

### ISSUE THREAD

**Issue by daidaiduoduo** [markgw/gaussianlda#1]
In the code, loglikehood (ll) is negative after the initilization, but it becomes positive after iterations. Although this is the same in the Gaussian LDA paper, I think loglikehood should be a negative number. Likehood is a probability value, which is less than 1, and its log is a negative number. Is it right?
And if the ll is positive, perplexity is exp(-ll), then ppl is smaller than 1?

**Comment by markgw** [comment]
I encountered this as well and assumed at first that it was a bug. Actually, it's not necessary incorrect.

Confusingly, log likelihood is actually not a probability, but a point value in the probability density function (PDF), since the distribution is continuous. Since it's a PDF, it doesn't sum to 1 (which doesn't make sense for a continuous function), but integrates to 1. This means that it's entirely possible for the PDF at a given point to have a value >1, if the normal distribution has a small variance, i.e. is mostly confined to a small part of the space.

This could happen for various reasons. One is just the nature of the embeddings used: if they use smaller numeric values, the PDFs will use higher values. Another is the priors: a small prior (co-)variance will encourage the Gaussians to be tighter, having smaller values in the covariance matrix and thus each focusing on a smaller set of words. The number of topics will also make a difference: more topics -> fewer words captured by each -> smaller covariances -> higher PDF values.

As a result of this distinction between probabilities and PDFs, the term "perplexity" is not really correct. (I've just followed the original authors' terminology.) The reason to compute this value is to check that it goes down during training. The absolute value has no meaning, since it depends on the factors above - i.e. it's not normalized in any way that makes it meaningful across different datasets, embeddings, etc.

**Comment by daidaiduoduo** [comment]
> I encountered this as well and assumed at first that it was a bug. Actually, it's not necessary incorrect.
> 
> Confusingly, log likelihood is actually not a probability, but a point value in the probability density function (PDF), since the distribution is continuous. Since it's a PDF, it doesn't sum to 1 (which doesn't make sense for a continuous function), but integrates to 1. This means that it's entirely possible for the PDF at a given point to have a value >1, if the normal distribution has a small variance, i.e. is mostly confined to a small part of the space.
> 
> This could happen for various reasons. One is just the nature of the embeddings used: if they use smaller numeric values, the PDFs will use higher values. Another is the priors: a small prior (co-)variance will encourage the Gaussians to be tighter, having smaller values in the covariance matrix and thus each focusing on a smaller set of words. The number of topics will also make a difference: more topics -> fewer words captured by each -> smaller covariances -> higher PDF values.
> 
> As a result of this distinction between probabilities and PDFs, the term "perplexity" is not really correct. (I've just followed the original authors' terminology.) The reason to compute this value is to check that it goes down during training. The absolute value has no meaning, since it depends on the factors above - i.e. it's not normalized in any way that makes it meaningful across different datasets, embeddings, etc.

Thank you for your patient answer~~ It's really helpful.
